"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, TeamDto } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { useChampionship } from "@/lib/championship";
import { toast } from "sonner";
import { AtSign, Check, MailCheck, Palette, Plus, ShieldCheck, Smartphone, UserCog, Users2, Wallet } from "lucide-react";

const initial = { teamName:"", shortCode:"", primaryColor:"#D3FF24", captainFullName:"", captainEmail:"", captainMobile:"" };
interface Created { teamId:string; teamName:string; shortCode:string; captainUserId:string; captainName:string; captainEmail:string; captainMobile:string; temporaryPassword:string; messageQueued:boolean }

export default function TeamManagementPage() {
  const user = useAuth((state)=>state.user);
  const active = useChampionship((state)=>state.active);
  const [teams,setTeams]=useState<TeamDto[]>([]); const [form,setForm]=useState(initial); const [saving,setSaving]=useState(false); const [created,setCreated]=useState<Created|null>(null);
  const role=user?.championships.find(item=>item.championshipId===active?.id)?.role;
  const allowed=role==="CHAMPIONSHIP_ADMIN";
  const load=()=>api.get<TeamDto[]>("/teams").then(({data})=>setTeams(data)).catch(()=>toast.error("Unable to load teams"));
  useEffect(()=>{ if(active) load(); },[active?.id]);
  async function submit(event:FormEvent){event.preventDefault();if(!active)return;setSaving(true);try{const {data}=await api.post<Created>(`/championships/${active.id}/admin/teams`,form);setCreated(data);setForm(initial);await load();toast.success("Team captain created and credentials queued");}catch(error:any){toast.error(error?.response?.data?.message||"Captain creation failed");}finally{setSaving(false);}}
  if(!allowed)return <div className="p-10"><h1 className="h-heading text-3xl">Championship Admin access required</h1></div>;
  if(!active)return <div className="p-10 label-cap">Select a championship first</div>;
  return <div className="min-h-screen p-5 md:p-10"><div className="mx-auto max-w-7xl"><div className="mb-8"><div className="label-cap text-primary">Franchise access</div><h1 className="h-heading mt-2 text-4xl font-bold md:text-5xl">Teams & captains</h1><p className="mt-3 max-w-2xl text-sm text-white/50">Create each franchise with one dedicated captain login. Credentials are securely queued through <span className="text-white">message_tracker</span>.</p></div>
  {active.status!=="ACTIVE"&&<div className="mb-6 rounded-2xl border border-warning/30 bg-warning/10 p-4 text-sm text-warning">Configure and activate this championship before creating teams.</div>}
  <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form onSubmit={submit} className="card-elev rounded-2xl p-6"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Plus size={18}/></div><div><h2 className="h-heading text-lg">Provision franchise</h2><p className="mt-1 text-xs text-white/40">Team identity + captain access</p></div></div><div className="space-y-4"><Field label="Team name"><input className="input" required value={form.teamName} onChange={e=>setForm({...form,teamName:e.target.value})} placeholder="NEML Smashers"/></Field><div className="grid grid-cols-[1fr_88px] gap-4"><Field label="Short code"><input className="input uppercase" maxLength={6} required value={form.shortCode} onChange={e=>setForm({...form,shortCode:e.target.value.toUpperCase()})} placeholder="NMS"/></Field><Field label="Colour"><label className="grid h-[46px] cursor-pointer place-items-center rounded-lg border border-white/10" style={{background:form.primaryColor+"22"}}><Palette size={18} style={{color:form.primaryColor}}/><input type="color" className="sr-only" value={form.primaryColor} onChange={e=>setForm({...form,primaryColor:e.target.value})}/></label></Field></div><div className="my-5 border-t border-white/10"/><Field label="Captain full name"><input className="input" required value={form.captainFullName} onChange={e=>setForm({...form,captainFullName:e.target.value})}/></Field><Field label="Captain email"><input className="input" type="email" required value={form.captainEmail} onChange={e=>setForm({...form,captainEmail:e.target.value})}/></Field><Field label="Captain mobile"><input className="input" type="tel" required value={form.captainMobile} onChange={e=>setForm({...form,captainMobile:e.target.value})}/></Field><button className="btn btn-primary mt-2 w-full py-3" disabled={saving||active.status!=="ACTIVE"}><UserCog size={16}/>{saving?"Provisioning…":"Create captain login"}</button></div></form>
  <div><div className="mb-4 flex items-center justify-between"><div><div className="label-cap">Current franchises</div><h2 className="h-heading mt-1 text-2xl">{teams.length} teams ready</h2></div><span className="chip chip-primary"><ShieldCheck size={12}/>Tenant scoped</span></div>{created&&<div className="mb-4 rounded-2xl border border-primary/30 bg-primary/5 p-5"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary text-black"><Check size={18}/></div><div><h3 className="h-heading">{created.teamName} provisioned</h3><p className="mt-1 text-xs text-white/45">{created.captainName} · {created.captainEmail}</p><div className="mt-3 rounded-lg border border-white/10 bg-black/20 px-3 py-2 font-mono text-sm text-white">{created.temporaryPassword}</div><p className="mt-2 text-[10px] text-white/35">One-time display—copy before leaving this screen.</p><div className="mt-3 inline-flex items-center gap-2 text-xs text-primary"><MailCheck size={14}/>{created.messageQueued?"Credential message queued":"Message not queued"}</div></div></div></div>}<div className="grid gap-4 md:grid-cols-2">{teams.map(team=><article key={team.id} className="card-elev rounded-2xl p-5 transition-transform duration-200 hover:-translate-y-1"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl font-bold" style={{background:team.primaryColor+"22",color:team.primaryColor,border:`1px solid ${team.primaryColor}55`}}>{team.shortCode}</div><span className="chip"><Users2 size={12}/>{team.totalPlayers} players</span></div><h3 className="h-heading mt-5 text-xl">{team.name}</h3><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4"><div className="text-xs text-white/40">Purse available</div><div className="flex items-center gap-1 text-sm font-semibold text-primary"><Wallet size={14}/>₹{Number(team.purseRemaining).toLocaleString("en-IN")}</div></div></article>)}{teams.length===0&&<div className="md:col-span-2 grid min-h-52 place-items-center rounded-2xl border border-dashed border-white/15 text-center"><div><Users2 className="mx-auto text-white/20" size={36}/><p className="mt-3 text-sm text-white/40">No teams yet. Provision the first captain.</p></div></div>}</div></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-3"><Hint icon={<AtSign size={15}/>} text="Email stored as login ID"/><Hint icon={<Smartphone size={15}/>} text="Mobile and email queued"/><Hint icon={<ShieldCheck size={15}/>} text="Login password is BCrypt hashed"/></div></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label-cap mb-2 block">{label}</span>{children}</label>}
function Hint({icon,text}:{icon:React.ReactNode;text:string}){return <div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.02] p-3 text-xs text-white/45"><span className="text-primary">{icon}</span>{text}</div>}
